spring.application.name=lab3
server.port=8080
# Gi?i h?n dung l??ng cho 1 file
spring.servlet.multipart.max-file-size=10MB

# Gi?i h?n t?ng dung l??ng c?a c? request (g?m file và d? li?u form)
spring.servlet.multipart.max-request-size=10MB